version: '3.2'

services:
  server1:
    build:
      context: ./server
    environment:
      - PORT=3000
      - DB_FILE=db1

  server2:
    build:
      context: ./server
    environment:
      - PORT=3000
      - DB_FILE=db2

  nginx:
    image: nginx:1.21.1
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
